# Generated by Django 5.2.1 on 2025-05-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da medico', max_length=200, verbose_name='Nome')),
                ('email', models.CharField(blank=True, help_text='Email da medico', max_length=100, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(help_text='Ex: XXXXXX-XXXX', max_length=11, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(help_text='Data de nascimento', verbose_name='Data de nascimento')),
                ('cpf', models.CharField(help_text='EX: XXX-XXX-XXX.XX', max_length=14, verbose_name='CPF')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('inativo', 'inativo')], default='Ativo', help_text='Status do medico', max_length=10, verbose_name='Status')),
                ('crm', models.CharField(help_text='Ex: CRM/UF XXXXXX', max_length=12, unique=True, verbose_name='CRM')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data de atualização', verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da paciente', max_length=200, verbose_name='Nome')),
                ('data_nascimento', models.DateField(help_text='Data de nascimento', verbose_name='Data de nascimento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Outro', 'Outro')], help_text='Sexo do paciente', max_length=10, verbose_name='Sexo')),
                ('cpf', models.CharField(help_text='EX: XXX-XXX-XXX.XX', max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(help_text='RG do paciente', max_length=12, verbose_name='RG')),
                ('nome_mae', models.CharField(help_text='Nome da mae', max_length=200, verbose_name='Nome mae')),
                ('nome_pai', models.CharField(blank=True, help_text='Nome da pai', max_length=200, verbose_name='Nome pai')),
                ('telefone_principal', models.CharField(help_text='Ex: XXXXXX-XXXX', max_length=11, unique=True, verbose_name='Telefone')),
                ('telefone_segundario', models.CharField(help_text='Ex: XXXXXX-XXXX', max_length=11, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, help_text='Email do paciente', max_length=100, unique=True, verbose_name='Email')),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A⁺', 'A⁺'), ('A⁻', 'A⁻'), ('B⁺', 'B⁺'), ('B⁻', 'B⁻'), ('AB⁺', 'AB⁺'), ('AB⁻', 'AB⁻'), ('O⁺', 'O⁺'), ('O⁻', 'O⁻')], help_text='Tipo Sanguineo do paciente', max_length=3, verbose_name='Tipo Sanguineo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data de atualização', verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='SetorAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Setor de atuação', max_length=120, unique=True, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data de atualização', verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da enfermeiro', max_length=200, verbose_name='Nome')),
                ('email', models.CharField(blank=True, help_text='Email do enfermeiro', max_length=100, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(help_text='Ex: XXXXXX-XXXX', max_length=11, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(help_text='Data de nascimento', verbose_name='Data de nascimento')),
                ('cpf', models.CharField(help_text='EX: XXX-XXX-XXX.XX', max_length=14, verbose_name='CPF')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('inativo', 'inativo')], default='Ativo', help_text='Status do enfermeiro', max_length=10, verbose_name='Status')),
                ('coren', models.CharField(help_text='Coren do enfermeiro', max_length=100, unique=True, verbose_name='Coren')),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], help_text='Turno do enfermeiro', max_length=10, verbose_name='Turno')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data de atualização', verbose_name='Atualizado em')),
                ('atuacao', models.ForeignKey(help_text='Atuação do enfermeiro', on_delete=django.db.models.deletion.RESTRICT, to='prontuario.setoratuacao', verbose_name='Setor')),
            ],
        ),
    ]
