# Generated by Django 5.2.1 on 2025-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setoratuacao',
            options={'verbose_name': 'Setor Atuação', 'verbose_name_plural': 'Setores Atuação'},
        ),
        migrations.AlterField(
            model_name='enfermeiro',
            name='cpf',
            field=models.CharField(help_text='EX: XXXXXXXXX', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='enfermeiro',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do enfermeiro', max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='cpf',
            field=models.CharField(help_text='EX: XXXXXXXXX', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='email',
            field=models.EmailField(blank=True, help_text='Email da medico', max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(help_text='EX: XXXXXXXXX', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do paciente', max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
