# Generated by Django 5.2.1 on 2025-05-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuario", "0002_alter_setoratuacao_options_alter_enfermeiro_cpf_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enfermeiro",
            options={
                "verbose_name": "Enfermeiro",
                "verbose_name_plural": "Enfermeiros",
            },
        ),
        migrations.AlterModelOptions(
            name="medicos",
            options={"verbose_name": "Medico", "verbose_name_plural": "Medicos"},
        ),
        migrations.AlterModelOptions(
            name="paciente",
            options={"verbose_name": "Paciente", "verbose_name_plural": "Pacientes"},
        ),
        migrations.AlterField(
            model_name="enfermeiro",
            name="coren",
            field=models.CharField(
                help_text="Coren do enfermeiro",
                max_length=20,
                unique=True,
                verbose_name="Ex: Coren-UF XXXXXX-Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="enfermeiro",
            name="cpf",
            field=models.CharField(
                help_text="EX: XXXXXXXXX",
                max_length=11,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="medicos",
            name="cpf",
            field=models.CharField(
                help_text="EX: XXXXXXXXX",
                max_length=11,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="cpf",
            field=models.CharField(
                help_text="EX: XXXXXXXXX",
                max_length=11,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(
                help_text="Nome do paciente", max_length=200, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="rg",
            field=models.CharField(
                help_text="RG do paciente",
                max_length=12,
                unique=True,
                verbose_name="RG",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone_segundario",
            field=models.CharField(
                blank=True,
                help_text="Ex: XXXXXX-XXXX",
                max_length=11,
                verbose_name="Telefone",
            ),
        ),
    ]
