# Generated by Django 5.2.1 on 2025-05-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuario", "0003_alter_enfermeiro_options_alter_medicos_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicos",
            name="crm",
            field=models.CharField(
                help_text="Ex: CRM/UF XXXXXX",
                max_length=13,
                unique=True,
                verbose_name="CRM",
            ),
        ),
    ]
