# Generated by Django 5.2.1 on 2025-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuario", "0004_alter_medicos_crm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="rg",
            field=models.CharField(
                help_text="RG do paciente", max_length=9, unique=True, verbose_name="RG"
            ),
        ),
    ]
