# Generated by Django 5.2.1 on 2025-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuario", "0006_alter_paciente_telefone_segundario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="telefone_segundario",
            field=models.CharField(
                blank=True,
                help_text="Ex: XXXXXX-XXXX",
                max_length=11,
                verbose_name="Telefone Segundario",
            ),
        ),
    ]
